### ISSUE TITLE
connect button should be disabled if username is empty

### ISSUE THREAD

**Issue by amarlearning** [amarlearning/spring-boot-websocket#1]
If `username` input field is empty, the `connect to` button should be disabled.
![png image 1000 x 600 pixels](https://user-images.githubusercontent.com/9383897/46814030-7c0f5180-cd95-11e8-92a1-6e796718001a.png)

**Comment by Kitsutypy** [comment]
In which file is this input field?

**Comment by jugendhacker** [comment]
Solved this with the PR...
